config/routes.rb
Rails.application.routes.draw do
  mount RailsPulse::Engine => '/admins/monitoring', as: 'rails_pulse'

  default_url_options host: ENV.fetch('HOST', 'localhost:3000')
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  root 'dashboard#welcome'

  devise_for :students, controllers: {
    registrations: 'student/registrations'
  }
  devise_for :admins, only: %i[sessions passwords confirmations], controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    confirmations: 'admin/confirmations'
  }

  namespace :admin do
    resources :students, only: %i[index new edit update]
    resources :courses, only: %i[index show new create edit update destroy]
    resources :enrollments, only: %i[index]
    resources :passwords, only: %i[new create edit update]
  end

  resources :contacts, only: %i[new create]
  resources :courses, only: %i[show index]

  post 'cookies/accept', to: 'cookies#accept'
end

app/models/student.rb
class Student < User
  default_scope { where(kind: :student) }

  PHONE_MINMAX_LENGTHS = {
    minimum: 10,
    maximum: 11
  }

  attribute :kind, :enum, default: :student

  has_many :enrollments, foreign_key: :user_id

  validates :name, :email, :phone, presence: true
  validates :email, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone, length: PHONE_MINMAX_LENGTHS

  scope :not_contacted, -> { where(contacted: false) }

  private

  def password_required?
    false
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < Admin::BaseController
  before_action :set_student, only: [:show, :edit, :update]

  def index
    @students = Student.order(created_at: :desc)
  end

  def show; end

  def edit; end

  def update
    if @student.update(student_params)
      redirect_to admin_students_path, notice: 'Aluno atualizado com sucesso.'
    else
      flash.now.alert = @student.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :email, :phone, :contacted, :enrolled)
  end
end

app/controllers/student/confirmations_controller.rb
# frozen_string_literal: true

class Student::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/student/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Student::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/student/passwords_controller.rb
# frozen_string_literal: true

class Student::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/student/registrations_controller.rb
# frozen_string_literal: true

class Student::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/student/sessions_controller.rb
# frozen_string_literal: true

class Student::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/student/unlocks_controller.rb
# frozen_string_literal: true

class Student::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/admin/students/_form.html.erb
<div class="m-10 p-4 border-1 shadow-sm">
  <%= form_for [:admin, @student], html: { class: "space-y-12 p-4" } do |f| %>
    <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 pb-12 md:grid-cols-3">
      <div>
        <h2 class="text-base font-semibold leading-7 text-gray-900"><%= title %></h2>
        <p class="mt-1 text-sm leading-6 text-gray-600"><%= @student.name %></p>
      </div>
      <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-2">
        <div class="sm:col-span-4">
          <%= f.label :name, "Nome", class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="mt-2">
            <%= f.text_field :name, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-red-600 sm:text-sm sm:leading-6", placeholder: "João Silva", required: true %>
          </div>
        </div>
        <div class="sm:col-span-4">
          <%= f.label :email, "Email", class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="mt-2">
            <%= f.email_field :email, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-red-600 sm:text-sm sm:leading-6", placeholder: "email@exemplo.com", required: true %>
          </div>
        </div>
        <div class="sm:col-span-4">
          <%= f.label :phone, "Telefone", class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="mt-2">
            <%= f.telephone_field :phone, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-red-600 sm:text-sm sm:leading-6", placeholder: "11999999999", required: true %>
          </div>
        </div>
        <div class="sm:col-span-4">
          <%= f.label :contacted, "Entrou em contato com o aluno?", class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="mt-2">
            <%= f.select :contacted, [["Sim", true], ["Não", false]], {}, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-red-600 sm:text-sm sm:leading-6" %>
          </div>
        </div>
        <div class="sm:col-span-4">
          <%= f.label :enrolled, "Aluno se matriculou?", class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="mt-2">
            <%= f.select :enrolled, [["Sim", true], ["Não", false]], {}, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-red-600 sm:text-sm sm:leading-6" %>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-6 flex items-center justify-end gap-x-6">
      <%= link_to "Cancelar", :back, class: "text-sm font-semibold leading-6 text-gray-900" %>
      <%= f.submit class: "rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600 hover:cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/admin/students/edit.html.erb
<% title = "Editar aluno" %>
<% description = "Modificar dados do aluno #{@student.name}" %>
<%= render "admin/students/form", title: title, description: description %>

app/views/admin/students/index.html.erb
<div class="m-5 border-2 rounded-md shadow-sm">
  <div class="m-2">
    <div class="px-4 sm:px-6 lg:px-8">
      <div class="sm:flex sm:items-center">
        <div class="sm:flex-auto">
          <h1 class="text-base font-semibold leading-6 text-gray-900">Alunos</h1>
          <p class="mt-2 text-sm text-gray-700">Lista de todos os alunos cadastrados.</p>
        </div>
        <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
          <%= link_to "Novo aluno", new_admin_student_path, class: "block rounded-md bg-red-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-red-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600" %>
        </div>
      </div>
      <div class="mt-8 flow-root">
        <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
            <table class="min-w-full divide-y divide-gray-300">
              <thead>
                <tr>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-3">Nome</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Email</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Telefone</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Contatado?</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Matriculado?</th>
                  <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-3">
                    <span class="sr-only">Editar</span>
                  </th>
                </tr>
              </thead>
              <tbody class="bg-white">
                <% if @students.any? %>
                  <% @students.each do |student| %>
                    <tr class="even:bg-gray-50">
                      <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-3"><%= student.name %></td>
                      <td class="max-w-xs px-3 py-4 text-sm text-gray-500 truncate"><%= student.email %></td>
                      <td class="max-w-xs px-3 py-4 text-sm text-gray-500 truncate"><%= student.phone %></td>
                      <td class="px-3 py-4 text-sm text-gray-500">
                        <% if student.contacted?%>
                          <span class="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">Sim</span>
                        <% else %>
                          <span class="inline-flex items-center rounded-md bg-red-50 px-2 py-1 text-xs font-medium text-red-700 ring-1 ring-inset ring-red-600/20">Não</span>
                        <% end %>
                      </td>
                      <td class="px-3 py-4 text-sm text-gray-500">
                        <% if student.enrolled? %>
                          <span class="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">Sim</span>
                        <% else %>
                          <span class="inline-flex items-center rounded-md bg-red-50 px-2 py-1 text-xs font-medium text-red-700 ring-1 ring-inset ring-red-600/20">Não</span>
                        <% end %>
                      </td>
                      <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-3">
                        <%= link_to "Editar", edit_admin_student_path(student), class: "text-red-600 hover:text-red-900" %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              <% else %>
                <tr class="even:bg-gray-50">
                  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-3" colspan="5">Nenhum aluno cadastrado.</td>
                </tr>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/students/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Studends#show</h1>
  <p>Find me in app/views/admin/studends/show.html.erb</p>
</div>