config/routes.rb
Rails.application.routes.draw do
  mount RailsPulse::Engine => '/admins/monitoring', as: 'rails_pulse'

  default_url_options host: ENV.fetch('HOST', 'localhost:3000')
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  root 'dashboard#welcome'

  devise_for :students, controllers: {
    registrations: 'student/registrations'
  }
  devise_for :admins, only: %i[sessions passwords confirmations], controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    confirmations: 'admin/confirmations'
  }

  namespace :admin do
    resources :students, only: %i[index new edit update]
    resources :courses, only: %i[index show new create edit update destroy]
    resources :enrollments, only: %i[index]
    resources :passwords, only: %i[new create edit update]
  end

  resources :contacts, only: %i[new create]
  resources :courses, only: %i[show index]

  post 'cookies/accept', to: 'cookies#accept'
end

app/views/shared/_alerts.html.erb
<% if flash.notice %>
  <div data-controller="alert" data-action="click->alert#dismiss" role="alert" class="rounded-xl border border-gray-100 p-4 bg-blue-100">
    <div class="flex items-start gap-4">
      <span class="text-green-600">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6" >
          <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
      </span>
      <div class="flex-1">
        <strong class="block font-medium text-gray-900"> Informação </strong>
        <p class="mt-1 text-sm text-gray-700"><%= flash.notice %></p>
      </div>
      <button @click="showNotice = false" class="text-gray-500 transition hover:text-gray-600">
        <span class="sr-only">Dismiss popup</span>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6" >
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>
  </div>
<% end %>
<% begin %>
  <% errors = resource.errors %>
<% rescue NameError %>
  <% errors = nil %>
<% end %>
<% if flash.alert || !errors.blank? %>
    <% message = flash.alert || errors&.full_messages&.join(", ") %>
    <div data-controller="alert" data-action="click->alert#dismiss" role="alert" class="rounded-xl border border-gray-100 p-4 bg-red-100">
      <div class="flex items-start gap-4">
        <span class="text-red-600">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m9-.75a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9 3.75h.008v.008H12v-.008Z" />
          </svg>
        </span>
        <div class="flex-1">
          <strong class="block font-medium text-red-900"> Alerta </strong>
          <p class="mt-1 text-sm text-gray-700"><%= message %></p>
        </div>
        <button @click="showNotice = false" class="text-gray-500 transition hover:text-gray-600">
          <span class="sr-only">Dismiss popup</span>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6" >
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
<% end %>

app/views/shared/_cookies.html.erb
<div id="cookie-banner" data-controller="cookies" class="fixed inset-x-0 bottom-0 z-50 p-4 transition-transform duration-300 ease-in-out">
  <div class="mx-auto max-w-7xl">
    <div
      class="flex items-center justify-between rounded-lg border border-gray-300 bg-white px-6 py-4 shadow-lg backdrop-blur-sm"
    >
      <div class="flex-1 mr-4">
        <p class="text-sm text-gray-700 font-medium">
          🍪 Nós usamos cookies para melhorar sua experiência. Ao continuar navegando, você concorda com nossa política de privacidade.
        </p>
      </div>

      <div class="flex items-center space-x-3">
        <%= button_to "Ok", cookies_accept_path, "data-action" => "cookies#accept", class: "px-4 py-2 bg-red-600 text-white text-sm font-medium rounded-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 transition-colors duration-200" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-black lg:grid lg:grid-cols-5">
  <div class="relative block h-32 lg:col-span-2 lg:h-full">
    <%= image_tag "botijao.jpg", class: "absolute inset-0 h-full w-full object-cover" %>
  </div>

  
  <div class="px-4 py-16 sm:px-6 lg:col-span-3 lg:px-8 bg-black">
    <p class="text-lg font-medium text-gray-300">Unidades</p>
    <div class="grid grid-cols-1 gap-8 sm:grid-cols-2">
      <div>
        <div class="py-3 flex items-center text-sm text-gray-800 before:flex-1 before:border-t before:border-gray-200 before:me-6 after:flex-1 after:border-t after:border-gray-200 after:ms-6 dark:text-white dark:before:border-neutral-600 dark:after:border-neutral-600">São Bernardo do Campo (SBC)</div>

        <div>
          <p>
            <span class="text-xs uppercase tracking-wide text-gray-100"> Contato </span>
            <a href="https://api.whatsapp.com/send?phone=5511982065921" class="flex text-2xl font-medium text-gray-300 hover:opacity-75 sm:text-2xl">
              11 98206-5921
              <i class="ml-2 mt-1 align-middle">
                <svg class="h-5 w-5 text-green-500 fill-current" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>WhatsApp</title><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z"/></svg>
              </i>
            </a>
          </p>

          <ul class="mt-8 space-y-2 text-sm text-gray-200">
            <p class="mt-4">
              <span class="text-xs uppercase tracking-wide text-gray-50"> Aulas </span>
            </p>
            <li>Durante a semana: das 9h às 12h, 19h às 21h</li>
            <li class="mb-4">Sábados: das 9h às 12h</li>
          </ul>

          <ul class="mt-8 space-y-2 text-sm">
            <p>
              <span class="text-xs uppercase tracking-wide text-gray-50"> Endereço </span>
            </p>
            <li>
              <a href="https://maps.app.goo.gl/uVeNGHYjWgkyLMpY7"
                  target="_blank"
                  rel="noopener noreferrer"
                  class="flex items-center justify-center gap-1.5 ltr:sm:justify-start rtl:sm:justify-end"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  class="size-5 shrink-0 text-gray-300"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  stroke-width="2"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"
                  />
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"
                  />
                </svg>
                <address class="-mt-0.5 flex-1 not-italic text-gray-200">
                  Rua Marechal Deodoro, N° 1805, São Bernardo do Campo, Brasil
                </address>
              </a>
            </li>
          </ul>
        </div>
      </div>

      <div>
        <div class="py-3 flex items-center text-sm text-gray-800 before:flex-1 before:border-t before:border-gray-200 before:me-6 after:flex-1 after:border-t after:border-gray-200 after:ms-6 dark:text-white dark:before:border-neutral-600 dark:after:border-neutral-600">Diadema</div>

          <p>
            <span class="text-xs uppercase tracking-wide text-gray-100"> Contato </span>
            <a href="https://api.whatsapp.com/send?phone=5511985755827" class="flex text-2xl font-medium text-gray-300 hover:opacity-75 sm:text-2xl">
              11 98575-5827
              <i class="ml-2 mt-1 align-middle">
                <svg class="h-5 w-5 text-green-500 fill-current" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>WhatsApp</title><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z"/></svg>
              </i>
            </a>
          </p>

          <ul class="mt-8 space-y-2 text-sm text-gray-200">
            <p class="mt-4">
              <span class="text-xs uppercase tracking-wide text-gray-50"> Aulas </span>
            </p>
            <li>Segundas e Quintas: das 19h às 21h</li>
            <li>Sábados: das 9h às 12h</li>
          </ul>

          <ul class="mt-8 space-y-2 text-sm">
              <p>
                <span class="text-xs uppercase tracking-wide text-gray-50"> Endereço </span>
              </p>
            <li>
              <a href="https://maps.app.goo.gl/tyiS2sDsFf6iBGuf6"
                  target="_blank"
                  rel="noopener noreferrer"
                  class="flex items-center justify-center gap-1.5 ltr:sm:justify-start rtl:sm:justify-end"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  class="size-5 shrink-0 text-gray-300"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  stroke-width="2"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"
                  />
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"
                  />
                </svg>
                <address class="-mt-0.5 flex-1 not-italic text-gray-200">
                  Avenida Alda, Nº 48, sala 26, Centro, Diadema, Brasil
                </address>
              </a>
            </li>
          </ul>
      </div>
    </div>

    <div class="mt-12 border-t border-gray-100 pt-12 grid grid-cols-1 gap-4 sm:grid-cols-2">
      <div>
        <p class="font-medium text-gray-300">Escola</p>
        <ul class="mt-6 space-y-4 text-sm">
          <li>
            <%= link_to "Cursos", courses_path, class: "text-gray-200 transition hover:opacity-75" %>
          </li>

          <li>
            <%= link_to "Contato", new_contact_path, class: "text-gray-200 transition hover:opacity-75" %>
          </li>
        </ul>
      </div>
    <div>
      <ul class="mt-8 flex gap-6">
          <li>
            <a
              href="https://www.facebook.com/kryptontreinamentos/?locale=pt_BR"
              rel="noreferrer"
              target="_blank"
              rel="noopener noreferrer"
              class="text-gray-200 transition hover:opacity-75"
            >
              <svg class="size-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path
                  fill-rule="evenodd"
                  d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z"
                  clip-rule="evenodd"
                />
              </svg>
            </a>
          </li>

          <li>
            <a
              href="https://www.instagram.com/krypton_treinamentos"
              rel="noreferrer"
              target="_blank"
              rel="noopener noreferrer"
              class="text-gray-200 transition hover:opacity-75"
            >
              <span class="sr-only">Instagram</span>

              <svg class="size-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path
                  fill-rule="evenodd"
                  d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z"
                  clip-rule="evenodd"
                />
              </svg>
            </a>
          </li>
        </ul>  
    </div>
    </div>

    <div class="mt-12 border-t border-gray-100 pt-12">
      <div class="sm:flex sm:items-center sm:justify-between">
        <ul class="flex flex-wrap gap-4 text-xs">
          <%# <li>
            <a href="#" class="text-gray-100 transition hover:opacity-75"> Terms & Conditions </a>
          </li>

          <li>
            <a href="#" class="text-gray-100 transition hover:opacity-75"> Privacy Policy </a>
          </li>

          <li>
            <a href="#" class="text-gray-100 transition hover:opacity-75"> Cookies </a>
          </li> %>
        </ul>

        <p class="mt-8 text-xs text-gray-100 sm:mt-0">
          &copy; <%= Time.now.year %>. Krypton Treinamentos.
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_hero_courses.html.erb
<dl class="grid max-w-xl grid-cols-1 gap-x-8 gap-y-16 lg:max-w-none lg:grid-cols-3 mt-8">
  <% @featured_courses.each do |course| %>
    <div class="flex flex-col">
      <dt class="flex gap-x-3 text-base font-semibold leading-7 text-gray-900">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-red-600">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.042A8.967 8.967 0 0 0 6 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 0 1 6 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 0 1 6-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0 0 18 18a8.967 8.967 0 0 0-6 2.292m0-14.25v14.25" />
        </svg>
        <%= course.name %>
      </dt>
      <dd class="mt-4 flex flex-auto flex-col text-base leading-7 text-gray-600">
        <p class="flex-auto"><%= course.description %></p>
        <p class="mt-6">
          <%= link_to course_path(course.id), class: "text-sm font-semibold leading-6 hover:underline text-red-600" do %>
            Saiba mais <span aria-hidden="true">→</span>
          <% end %>
        </p>
      </dd>
    </div>
  <% end %>
</dl>