config/routes.rb
Rails.application.routes.draw do
  mount RailsPulse::Engine => '/admins/monitoring', as: 'rails_pulse'

  default_url_options host: ENV.fetch('HOST', 'localhost:3000')
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  root 'dashboard#welcome'

  devise_for :students, controllers: {
    registrations: 'student/registrations'
  }
  devise_for :admins, only: %i[sessions passwords confirmations], controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    confirmations: 'admin/confirmations'
  }

  namespace :admin do
    resources :students, only: %i[index new edit update]
    resources :courses, only: %i[index show new create edit update destroy]
    resources :enrollments, only: %i[index]
    resources :passwords, only: %i[new create edit update]
  end

  resources :contacts, only: %i[new create]
  resources :courses, only: %i[show index]

  post 'cookies/accept', to: 'cookies#accept'
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :prepare_contact, only: [:new, :create]

  def new
    @email = params['email']
  end

  def create
    Student.transaction do
      @student = Student.new(student_params)
      @student.skip_confirmation!
      if course_params.blank?
        flash.now[:alert] = 'Selecione ao menos um curso'
        return render :new, status: :unprocessable_content
      end

      if @student.save
        course_params.each do |course_id|
          Enrollment.create!(course_id: course_id, user_id: @student.reload.id)
        end
        StudentMailer.with(student: @student,
                           courses: @student.enrollments.map(&:course))
                     .enrollment_email
                     .deliver_later
        NewEnrollmentMailer.notify_admins.deliver_later
        redirect_to root_path, notice: 'Salvamos seu contato, assim que possível entraremos em contato.'
      else
        flash.now[:alert] = @student.errors.full_messages.to_sentence
        @selected_course_ids = course_params
        render :new, status: :unprocessable_content, course_ids: @selected_course_ids
      end
    end
  end

  private

  def prepare_contact
    @student = Student.new
    @courses = Course.order(featured: :desc).limit(4)
  end

  def student_params
    params.require(:contact).permit(:name, :email, :phone).merge(current_sign_in_ip: request.remote_ip)
  end

  def course_params
    params.require(:enrollments).permit(course_ids: [])[:course_ids].compact_blank
  end
end

app/views/contacts/new.html.erb
<div class="relative isolate bg-white">
  <div class="mx-auto grid max-w-7xl grid-cols-1 lg:grid-cols-2">
    <div class="relative px-6 pb-20 pt-24 sm:pt-32 lg:static lg:px-8 lg:py-48">
      <div class="mx-auto max-w-xl lg:mx-0 lg:max-w-lg">
        <div class="absolute inset-y-0 left-0 -z-10 w-full overflow-hidden bg-gray-100 ring-1 ring-gray-900/10 lg:w-1/2">
          <svg class="absolute inset-0 h-full w-full stroke-red-300 [mask-image:radial-gradient(100%_100%_at_top_right,white,transparent)]" aria-hidden="true">
            <defs>
              <pattern id="83fd4e5a-9d52-42fc-97b6-718e5d7ee527" width="200" height="200" x="100%" y="-1" patternUnits="userSpaceOnUse">
                <path d="M130 200V.5M.5 .5H200" fill="none" />
              </pattern>
            </defs>
            <rect width="100%" height="100%" stroke-width="0" fill="white" />
            <svg x="100%" y="-1" class="overflow-visible fill-gray-50">
              <path d="M-470.5 0h201v201h-201Z" stroke-width="0" />
            </svg>
            <rect width="100%" height="100%" stroke-width="0" fill="url(#83fd4e5a-9d52-42fc-97b6-718e5d7ee527)" />
          </svg>
        </div>
        <h2 class="text-pretty text-4xl font-semibold tracking-tight text-gray-900 sm:text-5xl">Ficou interessado?</h2>
        <p class="mt-6 text-lg leading-8 text-gray-600">Nos informe seus dados e seja contatado assim que novas turmas estiverem disponíveis.</p>
        <dl class="mt-10 space-y-4 text-base leading-7 text-gray-600">
          <%# <div class="flex gap-x-4">
            <dt class="flex-none">
              <span class="sr-only">Address</span>
              <svg class="h-7 w-6 text-gray-400" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 21h19.5m-18-18v18m10.5-18v18m6-13.5V21M6.75 6.75h.75m-.75 3h.75m-.75 3h.75m3-6h.75m-.75 3h.75m-.75 3h.75M6.75 21v-3.375c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21M3 3h12m-.75 4.5H21m-3.75 3.75h.008v.008h-.008v-.008Zm0 3h.008v.008h-.008v-.008Zm0 3h.008v.008h-.008v-.008Z" />
              </svg>
            </dt>
            <dd>545 Mavis Island<br>Chicago, IL 99191</dd>
          </div>
          <div class="flex gap-x-4">
            <dt class="flex-none">
              <span class="sr-only">Telephone</span>
              <svg class="h-7 w-6 text-gray-400" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 6.75c0 8.284 6.716 15 15 15h2.25a2.25 2.25 0 0 0 2.25-2.25v-1.372c0-.516-.351-.966-.852-1.091l-4.423-1.106c-.44-.11-.902.055-1.173.417l-.97 1.293c-.282.376-.769.542-1.21.38a12.035 12.035 0 0 1-7.143-7.143c-.162-.441.004-.928.38-1.21l1.293-.97c.363-.271.527-.734.417-1.173L6.963 3.102a1.125 1.125 0 0 0-1.091-.852H4.5A2.25 2.25 0 0 0 2.25 4.5v2.25Z" />
              </svg>
            </dt>
            <dd><a class="hover:text-gray-900" href="tel:+1 (555) 234-5678">+1 (555) 234-5678</a></dd>
          </div>
          <div class="flex gap-x-4">
            <dt class="flex-none">
              <span class="sr-only">Email</span>
              <svg class="h-7 w-6 text-gray-400" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
                <path stroke-linecap="round" stroke-linejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 0 1-2.25 2.25h-15a2.25 2.25 0 0 1-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0 0 19.5 4.5h-15a2.25 2.25 0 0 0-2.25 2.25m19.5 0v.243a2.25 2.25 0 0 1-1.07 1.916l-7.5 4.615a2.25 2.25 0 0 1-2.36 0L3.32 8.91a2.25 2.25 0 0 1-1.07-1.916V6.75" />
              </svg>
            </dt>
            <dd><a class="hover:text-gray-900" href="mailto:hello@example.com">hello@example.com</a></dd>
          </div> %>
        </dl>
      </div>
    </div>
    <%= form_for @student, as: :contact, url: contacts_path, html: { class: "px-6 pb-24 pt-20 sm:pb-32 lg:px-8 lg:py-48" } do |f| %>
      <div class="mx-auto max-w-xl lg:mr-0 lg:max-w-lg">
        <div class="grid grid-cols-1 gap-x-8 gap-y-6 sm:grid-cols-2">
          <div class="sm:col-span-2">
            <%= label :name, "Nome", class: "block text-sm font-semibold leading-6 text-gray-900" %>
            <div class="mt-2.5">
              <%= f.text_field :name, class: "block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-red-600 sm:text-sm sm:leading-6" %>
            </div>
          </div>
          <div class="sm:col-span-2">
            <%= label :email, "Email", class: "block text-sm font-semibold leading-6 text-gray-900" %>
            <div class="mt-2.5">
              <%= f.text_field :email, value: @email, class: "block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-red-600 sm:text-sm sm:leading-6" %>
            </div>
          </div>
          <div class="sm:col-span-2">
            <%= label :phone, "Telefone para contato", class: "block text-sm font-semibold leading-6 text-gray-900" %>
            <div class="mt-2.5">
              <%= f.phone_field :phone, class: "block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-red-600 sm:text-sm sm:leading-6" %>
            </div>
          </div>
          <h2 class="mt-2.5 font-medium text-gray-900">Cursos de interesse</h2>
          <div class="sm:col-span-2">
            <div class="grid grid-cols-1 gap-x-4 gap-y-4 sm:grid-cols-2">
              <%= collection_check_boxes :enrollments, :course_ids, @courses, :id, :name do |box| %>
                <div class="space-y-2">
                  <%= box.label class: "flex cursor-pointer items-start gap-4 rounded-lg border border-gray-200 p-4 transition hover:bg-gray-50 has-[:checked]:bg-red-50" do %>
                    <div class="flex items-center">
                      <%= box.check_box class: "size-4 rounded border-gray-300 accent-red-500 text-red-500 checked:bg-red-500 focus:ring-red-500 active:ring-red-500", checked: (params[:course_id] == box.value.to_s || @selected_course_ids&.include?(box.value.to_s)) ? 'checked' : '' %>
                      <div>
                        <strong class="ml-2 font-medium text-gray-900"><%= box.text %></strong>
                      </div>
                    </div>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="mt-8 flex justify-end">
          <%= f.submit "Registrar dados para contato", class: "rounded-md bg-red-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-red-500 hover:cursor-pointer focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600" %>
        </div>
      </div>
      </form>
    <% end %>
  </div>
</div>